export const ADD_USER = 'ADD_USER'
export const ADD_BUSINESS = 'ADD_BUSINESS'
export const ADD_ISLOGIN = 'ADD_ISLOGIN'
export const SET_ADDRESS = 'SET_ADDRESS'
export const SET_TOTALVALUE = 'SET_TOTALVALUE'
